[versions]
androidGradlePlugin = "8.1.1"
androidxComposeBom = "2023.09.01"

composeCompiler = "1.5.3"
kotlin = "1.9.10"

compileSdk = "34"
minSdk = "21"
targetSdk = "33"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
